version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - ./db/spydr.sql:/docker-entrypoint-initdb.d/10-spydr.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  api:
    build:
      context: ./api
    command: ["node", "./build/index.js"]
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres:5432/postgres
      NODE_ENV: production
      PORT: 8000
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - ./api/server:/api/server
      - /api/node_modules
  # cli:
  #   build:
  #     context: ./cli
  #   command: node --harmony index.js
  #   depends_on:
  #     - api
  #   environment:
  #     DATABASE_URL: postgres://postgres@postgres:5432/postgres
  #     SPYDR_API: http://api:8000
  #     NODE_ENV: production
  #   ports:
  #     - "5555:5555"
  web:
    build:
      context: ./web
    command: ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --history-api-fallback --host 0.0.0.0 --port 7070 --open
    depends_on:
      - api
      - postgres
    environment:
      SPYDR_API: http://0.0.0.0:8000
      NODE_ENV: production
      PORT: 7070
    ports:
      - "7070:7070"
    tty: true
    volumes:
      - ./web/src:/web/src
      - /web/node_modules
