// Igrms
export const FETCH_IGRM_USERS_PENDING = 'FETCH_IGRM_USERS_PENDING';
export const FETCH_IGRM_USERS_SUCCESS = 'FETCH_IGRM_USERS_SUCCESS';
export const FETCH_IGRM_USERS_FAILURE = 'FETCH_IGRM_USERS_FAILURE';
export const FETCH_IGRM_USER_PENDING = 'FETCH_IGRM_USER_PENDING';
export const FETCH_IGRM_USER_SUCCESS = 'FETCH_IGRM_USER_SUCCESS';
export const FETCH_IGRM_USER_FAILURE = 'FETCH_IGRM_USER_FAILURE';
export const FETCH_IGRM_FEED_PENDING = 'FETCH_IGRM_FEED_PENDING';
export const FETCH_IGRM_FEED_SUCCESS = 'FETCH_IGRM_FEED_SUCCESS';
export const FETCH_IGRM_FEED_FAILURE = 'FETCH_IGRM_FEED_FAILURE';

// Rdts
export const FETCH_RDT_USERS_PENDING = 'FETCH_RDT_USERS_PENDING';
export const FETCH_RDT_USERS_SUCCESS = 'FETCH_RDT_USERS_SUCCESS';
export const FETCH_RDT_USERS_FAILURE = 'FETCH_RDT_USERS_FAILURE';
export const FETCH_RDT_USER_PENDING = 'FETCH_RDT_USER_PENDING';
export const FETCH_RDT_USER_SUCCESS = 'FETCH_RDT_USER_SUCCESS';
export const FETCH_RDT_USER_FAILURE = 'FETCH_RDT_USER_FAILURE';
export const FETCH_RDT_FEED_PENDING = 'FETCH_RDT_FEED_PENDING';
export const FETCH_RDT_FEED_SUCCESS = 'FETCH_RDT_FEED_SUCCESS';
export const FETCH_RDT_FEED_FAILURE = 'FETCH_RDT_FEED_FAILURE';


// Yts
export const FETCH_YTS_CHANNELS_PENDING = 'FETCH_YTS_CHANNELS_PENDING';
export const FETCH_YTS_CHANNELS_SUCCESS = 'FETCH_YTS_CHANNELS_SUCCESS';
export const FETCH_YTS_CHANNELS_FAILURE = 'FETCH_YTS_CHANNELS_FAILURE';
export const FETCH_YTS_CHANNEL_PENDING = 'FETCH_YTS_CHANNEL_PENDING';
export const FETCH_YTS_CHANNEL_SUCCESS = 'FETCH_YTS_CHANNEL_SUCCESS';
export const FETCH_YTS_CHANNEL_FAILURE = 'FETCH_YTS_CHANNEL_FAILURE';
export const FETCH_YTS_FEED_PENDING = 'FETCH_YTS_FEED_PENDING';
export const FETCH_YTS_FEED_SUCCESS = 'FETCH_YTS_FEED_SUCCESS';
export const FETCH_YTS_FEED_FAILURE = 'FETCH_YTS_FEED_FAILURE';
export const UPDATE_YTS_VIDEO_PENDING = 'UPDATE_YTS_VIDEO_PENDING';
export const UPDATE_YTS_VIDEO_SUCCESS = 'UPDATE_YTS_VIDEO_SUCCESS';
export const UPDATE_YTS_VIDEO_FAILURE = 'UPDATE_YTS_VIDEO_FAILURE';

// User
export const AUTHORIZE_USER_SUCCESS = 'AUTHORIZE_USER_SUCCESS';
export const AUTHORIZE_USER_FAILURE = 'AUTHORIZE_USER_FAILURE';